org.gradle.parallel=true
org.gradle.java.home=E:/JDK25

# Mod Properties
mod_name=Collapsible Game Rules
mod_version=1.0.46+26.3
maven_group=net.instantgratification
archives_base_name=collapsible-game-rules

# Dependencies
minecraft_version=26.3

# Fabric
fabric_version=0.161.0+26.3
fabric_loader_version=0.19.5

# Loom
fabric.loom.suppressJavaCompatibilityChecks=true
loom.suppressJavaCompatibilityChecks=true

# DasikLibrary
dasik_library_version=1.9.2

# Publishing
modrinth_id=lObgjyJl
curseforge_id=1468932
github_repo=Rifaditya/Collapsible-Game-Rule-Screen
